name: Douji

services:
  frontend:
    extends:
      file: docker-compose.common.yaml
      service: frontend
    build:
      target: dev
    volumes:
      - ./Frontend:/app:ro
      - ./Frontend/.next:/app/.next
  backend:
    extends:
      file: docker-compose.common.yaml
      service: backend
    build:
      args:
        - BUILD_CONFIGURATION=Debug
      target: base
    volumes:
      - ./Backend:/app:ro
      - ./Backend/bin:/app/bin
      - ./Backend/obj:/app/obj
    entrypoint: dotnet run
  reverse_proxy:
    extends:
      file: docker-compose.common.yaml
      service: reverse_proxy
    environment:
      - DOUJI_DEV=1
    volumes:
      - ./dev_certs:/etc/ssl/douji:ro