name: Douji

volumes:
  ssl_certs:

services:
  frontend:
    extends:
      file: docker-compose.common.yaml
      service: frontend
    build:
      target: prod
  backend:
    extends:
      file: docker-compose.common.yaml
      service: backend
    build:
      target: final
  reverse_proxy:
    extends:
      file: docker-compose.common.yaml
      service: reverse_proxy
    environment:
      - DOUJI_DEV=0
    volumes:
      - ssl_certs:/etc/letsencrypt
