name: Douji

volumes:
  ssl_certs:

services:
  frontend:
    extends:
      file: docker-compose.common.yaml
      service: frontend
    build:
      target: prod
    restart: unless-stopped
  backend:
    extends:
      file: docker-compose.common.yaml
      service: backend
    build:
      target: final
      args:
        - BUILD_CONFIGURATION=Release
    restart: unless-stopped
  reverse_proxy:
    extends:
      file: docker-compose.common.yaml
      service: reverse_proxy
    environment:
      - DOUJI_DEV=0
    volumes:
      - ssl_certs:/etc/ssl/douji
      - lets_encrypt:/etc/letsencrypt
    restart: unless-stopped
